
num1 = float(input("Enter the first number: "))
num2 = float(input("Enter the second number: "))
print("\n--- Arithmetic Operations ---")
print(f"Numbers entered: {num1}, {num2}")
print(f"Sum: {num1 + num2}")
print(f"Difference: {num1 - num2}")
print(f"Product: {num1 * num2}")
print(f"Integer Quotient: {num1 // num2}")
print(f"Remainder: {num1 % num2}")
print(f"Fractional Quotient: {num1 / num2:.2f}")
